// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarDealership.Migrations
{
    [DbContext(typeof(DB_Context))]
    [Migration("20251102184834_AddVehicleImage")]
    partial class AddVehicleImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("CarDealership.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body_type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("From")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fuel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kilometers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SPZ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body_type = "Kombi",
                            Brand = "Škoda",
                            From = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fuel = "Benzín",
                            Image = "https://cdn.skoda-storyboard.com/2020/01/octavia-combi-2020-exterior-front.jpg",
                            Kilometers = 84500,
                            Model = "Octavia",
                            Note = "Servisní knížka, po prvním majiteli. Vozidlo je v perfektním technickém stavu a nikdy nebylo havarováno.",
                            SPZ = "4AN 5623",
                            Status = "Dostupné",
                            Year = 2019
                        },
                        new
                        {
                            Id = 2,
                            Body_type = "Hatchback",
                            Brand = "Volkswagen",
                            From = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fuel = "Nafta",
                            Image = "https://cdn.motor1.com/images/mgl/0x0v1/s1/2020-volkswagen-golf.jpg",
                            Kilometers = 51200,
                            Model = "Golf",
                            Note = "Automat DSG, pravidelně servisováno u autorizovaného dealera. Interiér bez známek opotřebení, vůz po nekuřákovi.",
                            SPZ = "2BC 7398",
                            Status = "Dostupné",
                            Year = 2020
                        },
                        new
                        {
                            Id = 3,
                            Body_type = "Sedan",
                            Brand = "BMW",
                            From = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fuel = "Nafta",
                            Image = "https://cdn.bmwblog.com/wp-content/uploads/2016/11/BMW-3-Series-F30-320d-M-Sport.jpg",
                            Kilometers = 125000,
                            Model = "320d",
                            Note = "Sportovní paket M Performance, výborná dynamika a komfortní podvozek. Vozidlo bylo čerstvě po velkém servisu.",
                            SPZ = "7AC 4521",
                            Status = "Rezervováno",
                            Year = 2017
                        },
                        new
                        {
                            Id = 4,
                            Body_type = "SUV",
                            Brand = "Peugeot",
                            From = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fuel = "Hybrid",
                            Image = "https://cdn.motor1.com/images/mgl/Q7jlp/s1/2022-peugeot-3008-hybrid.jpg",
                            Kilometers = 18500,
                            Model = "3008",
                            Note = "Plug-in hybrid s nízkým nájezdem a kompletní výbavou GT Line. Auto v tovární záruce a bez jediné závady.",
                            SPZ = "1AF 9810",
                            Status = "Dostupné",
                            Year = 2022
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
